[phases.install]
cmds = [
  "cd Inventory_management/backend && npm install",
  "cd Inventory_management/frontend && npm install"
]

[phases.build]
cmds = ["cd Inventory_management/frontend && npm run build"]

[start]
cmd = "node Inventory_management/backend/server.js"
